accounts/urls.py
from django.urls import path
from .import views




app_name = 'accounts'

urlpatterns = [
    path('signup/', views.registerView, name='signup'),
    path('<pk>/update', views.UserEditView.as_view(), name="edit_profile")
    
]

blog/urls.py
from django import views
from django.urls import path

from blog.views import  book_list, Post_list, post_detail, profileView, loginView, logoutView, contactView, aboutView



app_name = 'blog'

urlpatterns = [
    path("contact/", contactView, name="contact"),
    path("about/", aboutView, name="about"),
    path("login/", loginView, name="login"),
    path('profile/', profileView, name='profile'),
    path('profile/', logoutView, name="logout"),
    path("book_list/", book_list),
    path("", Post_list ),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', post_detail, name= 'post_detail'),
    ]

ecommerce/urls.py
from django.urls import path
from ecommerce.views import MyViews, lindi



urlpatterns = [
    path("", lindi ),
    path('about/', MyViews.as_view())
    ]

introtodjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path("ecom/", include("ecommerce.urls")),
    path('', include("accounts.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from pytz import common_timezones_set

# Create your models here.
class Book(models.Model):
    title = models.CharField(max_length=225)
    subtitle = models.CharField(max_length=225)
    author = models.CharField(max_length=225)
    isbn = models.CharField(max_length=13)

    def __str__(self):
        return self.title

class Post (models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )
    title = models.CharField(max_length=250)
    post_image = models.ImageField(blank = True, null = True)
    slug = models.CharField(max_length=250, unique_for_date= 'publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name= 'blog_post')
    body = models.TextField()
    publish = models.DateTimeField(default= timezone.now)
    created = models.DateTimeField(auto_now_add = True)
    updated = models.DateTimeField(auto_now = True)
    status = models.CharField(max_length=10, choices = STATUS_CHOICES, default = 'draft')
    
    class Meta : 
        ordering = ('-publish',)

    def __str__(self) :
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year, self.publish.month, self.publish.day, self.slug])

class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete = models.CASCADE, related_name = 'comments')
    name = models.CharField(max_length = 80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add = True)
    updated = models.DateTimeField(auto_now = True)
    active = models.BooleanField(default = True)


    class Meta :
        ordering = ('created',)

    def __str__ (Self):
        return f'Comment by {Self.name} on {Self.post}' 

ecommerce/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


#create user form as a class
class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password']

blog/forms.py
from dataclasses import fields
from django import forms
from.models import Comment
from django import forms




class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.urls import reverse_lazy
from django.views.generic import UpdateView
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.models import User
# from requests import request
from .forms import CreateUserForm

# Create your views here.


def registerView(request):
    form = CreateUserForm()
    if  request.method =='POST':
        if form.is_valid():
          form.save()
          username = form.cleaned_data['username']
          email = form.cleaned_data['email']
          password = form.cleaned_data['password']
          user = authenticate(username=username, password=password, email=email)
          login(request, user)
          messages.success(redirect, 'Account created successfully')
          return redirect('blog:profile')
    else:
        form = CreateUserForm()
    return render(request, 'registration/signup.html', {'form':form})

class UserEditView(UpdateView):
    model = User
    form_class = UserChangeForm
    template_name = 'registration/editprofile.html'
    success_url = reverse_lazy ("blog:profile")

blog/views.py
from re import template
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.views.generic import TemplateView, ListView
from .models import Book, Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from.forms import CommentForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm 
from django.contrib.auth.decorators import login_required



# Create your views here.
@login_required(login_url='blog:login')
def profileView(request): 
    return render(request, 'profile.html', { })

#Class based view
class MyViews(TemplateView): 
    template_name = 'index.html'

def book_list(request):
    book = Book.objects.all()
    return render(request, "book_list.html", {"books": book})
   
#View for all posts
def  Post_list(request):
    objects_list = Post.objects.all()
    paginator = Paginator(objects_list, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)


    return render(request, "index.html", {"page":page, "posts" : posts})

#View for single post
def post_detail (request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year, publish__month=month, publish__day=day)
    comments = post.comments.filter(active=True)
    new_comment = None

    if request.method == 'POST': 
        comment_form = CommentForm(data = request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit = False)
            new_comment.post = post
            new_comment.save()
    else :
        comment_form = CommentForm()
    return render(request, 'post_detail.html', {'new_comment': new_comment, 'comments': comments, 'comment_form': comment_form, 'post' : post})

def loginView(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data = request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login (request,user)
                messages.info(request, f"You are now logged in as {username}.")
                return redirect("blog:profile")
            else:
                messages.error(request, f"Invalid username or password.")
        else:
            messages.error(request, f"Devil is a LIAR!!")
    form = AuthenticationForm()
    return render(request, 'authenticate/login.html', context = {"form":form})


def logoutView(request):
    logout(request)
    return redirect('/')

def contactView(request):
    return render(request, "contact.html", {})

def aboutView(request):
    return render(request, "about.html", {})

ecommerce/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import View
# Create your views here.

def lindi(request): 
    return HttpResponse("Wassup!")

#Class based view
class MyViews(View):
    def get(self, request):
        return HttpResponse('This is CBV')

blog/templates/about.html
{% extends 'base.html' %}

blog/templates/authenticate/login.html
{% extends "base.html" %}
{% block content %}

{% load crispy_forms_tags %}

<div class="login_wrapper">
    <div class="container">
        <!-- Login -->
        <h2>Log In</h2>
        <form method = "post" class="form">
            {% csrf_token %}
            {{form|crispy}}
            <button type="submit">Login</button>
            <p class="text-center">Hahaha You don't have an account <a href="#">Create an account!</a>.</p>
        </form>
    </div>
</div>
{% endblock%}

blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/app.css'%}">
    <link rel="stylesheet" href="{% static 'css/mobile.css'%}">
    
</head>
<body>
    <nav>
        <div class="logo"><h1>Fashion Blog</h1></div>
        <ul class="nav-links">
            <li><a href="">Home</a></li>
            <li><a href="{% url 'blog:about' %}">About</a></li>
            <li><a href="{% url 'blog:contact' %}">Contact</a></li>
            <li><a href="">Blog</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'blog:logout' %}">Logout</a></li>
            {% else %}
            
            <li class="nav-item"><a href="{% url 'blog:login' %}" class="nav-liks">Login</a></li>
            <li><a href="{% url 'accounts:signup' %}">SignUp</a></li>
            {% endif %}

            {% if request.user_authenticated %}
            <li>Heyy! {{request.user}}</li>
            {% endif %}

        </ul>
        <div class="burger">
            <div class="line1"></div>
            <div class="line2"></div>
            <div class="line3"></div>
        </div>
    </nav>

    <div class="container mt-5">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-danger mt-5" role="alert">
                {{ message }}
                </div>
            {% endfor %}
        {% endif %}
    </div>

    {% block content %}

    {% endblock content %}

    
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"></script>
<!-- <script src="{% static 'js/app.js'%}">   
</script> -->
</body>
</html>

blog/templates/book_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>my book list</h1>
    {%for book in books %}
    <ul>
    <Li>title: {{book.title}} </Li>
    <Li>subtitle: {{book.subtitle}}</Li>
    <Li>author: {{book.author}}</Li>
    <Li>isbn: {{book.isbn}}</Li>
    </ul>
    {%endfor%}
</body>
</html>

blog/templates/contact.html
{% extends 'base.html' %}

blog/templates/index.html
{% extends "base.html" %}


{% block content %}

    <!-- {% load static %} -->

    
    <!-- <img src="{% static 'images/original.jpg' %}"> -->
    


    <h1>Tell Me Why Are We So Blind To See That The Ones We Hurt Are You And Me.</h1>
    {% for post in posts %}

    <h2>
        <a href=" {{ post.get_absolute_url }} ">
        {{post.title}}
        </a>
    </h2>
    {% if post.post_image %}
    <img src="{{ post.post_image.url }}" alt="" width="300" height="400">
    {% endif %}

    <p class="date">
        Published {{post.author}} by {{post.author}}
    </p>

    {{post.slug}}

    <p>{{post.body|truncatewords:30|linebreaks}}</p>

    {{post.publish}}

    {% endfor %}

{% include "pagination.html" with page=posts %}

{% endblock content %} 

blog/templates/pagination.html
<div class="pagination container justify-content-center">
    <ul class="pagination">
        <li class="page-item">
            {% if page.has_previous %}
               <a href="?page={{page.previous_page_number}}" class="page-link">Previous</a>
            {% endif %}
            </li>
            <li class="page-item page-link">
                Page {{ page.number }}
            </li>
            <li class="page-item page-link"> of </li>
            <li class="page-item page-link">page{{ page.number }} of {{ page.paginator.num_pages }}</li>
            <li class="page-item">
                {% if page.has_next %}
                <a href="?page={{page.next_page_number}}" class="page-link">Next</a>
                {% endif %}
            </li>
            
               
            
        </li>
    </ul>
    
</div>

blog/templates/post_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}{{ post.title}}{% endblock %}
{% block content %}





    <h1> {{post.title}}</h1>

    <p class="date">
        Published {{post.author}} by {{post.author}}
    </p>
     <p>{{post.body|linebreaks}}</p>

    <!-- comment -->
    <div class="container">

    {% with comment.count as total_comments%}
    <h2>
        {{total_comments}} comment {{total_comments|pluralize}}
    </h2>
    {% endwith %}

    {% for comment in comments %}
    <div class="comment">
        <p class="info">Comment{{forloop.counter}} by {{comment.name}} {{comment.created}}</p>
        {{comment.body|linebreaks}}
    </div>
    {% empty %}
    <p>No Comment</p>
    {% endfor %}
    {% if new_comment%}
    <h2>Your comment has been added</h2>

    {% else %}
    <h2>Add new comment</h2>
    <form method="POST">
        {{ comment_form|crispy }}
        {% csrf_token %}
        <p><input type="submit" value="Add comment"></p>
    </form>
    {% endif %}
</div>
   
{% endblock %} 

blog/templates/profile.html
{% extends "base.html" %}
{% block content %}
<a href="{% url 'accounts:edit_profile' user.id %}">edit profile</a>
{% endblock %}